formatter: "markdown table"
version: ""
header-from: main.tf
footer-from: ""
recursive:
  enabled: false
  path: modules
sections:
  hide: []
  show: []
content: |-
  # Inputs

  {{ .Inputs }}

  # Outputs

  {{ .Outputs }}

  # Resources

  {{ .Resources }}

  # Requirements

  {{ .Requirements }}

  # Providers

  {{ .Providers }}

output:
  file: "INPUTS.md"
  mode: replace
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->
sort:
  enabled: true
  by: name
settings:
  anchor: true
  color: true
  default: true
  description: false
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true
